### ISSUE TITLE
Circular import issue on development branch for Blender 4.0

### ISSUE THREAD

**Issue by jdavies** [oRazeD/GrabDoc#4]
I downloaded the Dev  branch from GitHub today (Jan 4, 2024 at 15:30  in Phoenix) and got the follow error trace in the info window of Blender when  I checked the chekcbox to activate the newly installed GrabDoc addon. I did not have an earlier version installed: ```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\jeffd\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\GrabDoc-dev\__init__.py", line 28, in <module>
    modules.append(importlib.import_module(f".{module_name}", __package__))
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\jeffd\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\GrabDoc-dev\operators\operators.py", line 12, in <module>
    from ..utils.scene import scene_setup, remove_setup
  File "C:\Users\jeffd\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\GrabDoc-dev\utils\scene.py", line 6, in <module>
    from ..utils.generic import is_camera_in_3d_view
  File "C:\Users\jeffd\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\GrabDoc-dev\utils\generic.py", line 8, in <module>
    from ..__init__ import bl_info
  File "C:\Users\jeffd\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\GrabDoc-dev\__init__.py", line 28, in <module>
    modules.append(importlib.import_module(f".{module_name}", __package__))
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\jeffd\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\GrabDoc-dev\operators\material.py", line 7, in <module>
    from ..utils.generic import UseSelectedOnly, OpInfo
ImportError: cannot import name 'UseSelectedOnly' from partially initialized module 'GrabDoc-dev.utils.generic' (most likely due to a circular import) (C:\Users\jeffd\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\GrabDoc-dev\utils\generic.py)

```

**Comment by oRazeD** [comment]
Hey @jdavies, try the latest build. I don't think this was fixed in any particular commit but it shouldn't be happening at this point.
